/*
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: project.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Project.Protocol {

  /// <summary>Holder for reflection information generated from project.proto</summary>
  public static partial class ProjectReflection {

    #region Descriptor
    /// <summary>File descriptor for project.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProjectReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1wcm9qZWN0LnByb3RvEhBwcm9qZWN0LnByb3RvY29sIjYKBFVzZXISCgoC",
            "aWQYASABKAkSEAoIdXNlcm5hbWUYAiABKAkSEAoIcGFzc3dvcmQYAyABKAki",
            "hAEKCEV4Y3Vyc2llEhcKD29iaWVjdGl2Vml6aXRhdBgBIAEoCRISCgpvcmFQ",
            "bGVjYXJlGAIgASgJEhYKDmZpcm1hVHJhbnNwb3J0GAMgASgJEgwKBHByZXQY",
            "BCABKAkSGQoRbG9jdXJpRGlzcG9uaWJpbGUYBSABKAkSCgoCaWQYBiABKAki",
            "bgoFQmlsZXQSFQoNbnVtYXJQZXJzb2FuZRgBIAEoCRISCgpudW1lQ2xpZW50",
            "GAIgASgJEhoKEm51bWFyVGVsZWZvbkNsaWVudBgDIAEoCRISCgppZEV4Y3Vy",
            "c2llGAQgASgJEgoKAmlkGAUgASgJIrcCCg5Qcm9qZWN0UmVxdWVzdBIzCgR0",
            "eXBlGAEgASgOMiUucHJvamVjdC5wcm90b2NvbC5Qcm9qZWN0UmVxdWVzdC5U",
            "eXBlEiQKBHVzZXIYAiABKAsyFi5wcm9qZWN0LnByb3RvY29sLlVzZXISJgoF",
            "YmlsZXQYAyABKAsyFy5wcm9qZWN0LnByb3RvY29sLkJpbGV0EiwKCGV4Y3Vy",
            "c2llGAQgASgLMhoucHJvamVjdC5wcm90b2NvbC5FeGN1cnNpZRIOCgZvcmFt",
            "aW4YBSABKAkSDgoGb3JhbWF4GAYgASgJIlQKBFR5cGUSCQoFTE9HSU4QABIK",
            "CgZMT0dPVVQQARINCglHRVRfVFJJUFMQAhIWChJHRVRfRklMVEVSRURfVFJJ",
            "UFMQAxIOCgpCVVlfVElDS0VUEAQipgIKD1Byb2plY3RSZXNwb25zZRI0CgR0",
            "eXBlGAEgASgOMiYucHJvamVjdC5wcm90b2NvbC5Qcm9qZWN0UmVzcG9uc2Uu",
            "VHlwZRIUCgxlcnJvck1lc3NhZ2UYAiABKAkSJAoEdXNlchgDIAEoCzIWLnBy",
            "b2plY3QucHJvdG9jb2wuVXNlchIsCghleGN1cnNpaRgEIAMoCzIaLnByb2pl",
            "Y3QucHJvdG9jb2wuRXhjdXJzaWUSJgoFYmlsZXQYBSABKAsyFy5wcm9qZWN0",
            "LnByb3RvY29sLkJpbGV0IksKBFR5cGUSBgoCT0sQABIJCgVFUlJPUhABEgkK",
            "BVRSSVBTEAISEgoORklMVEVSRURfVFJJUFMQAxIRCg1CT1VHSFRfVElDS0VU",
            "EARCNQohcHJvamVjdC5uZXR3b3JrLnByb3RvYnVmZnByb3RvY29sQhBQcm9q",
            "ZWN0UHJvdG9idWZzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Project.Protocol.User), global::Project.Protocol.User.Parser, new[]{ "Id", "Username", "Password" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Project.Protocol.Excursie), global::Project.Protocol.Excursie.Parser, new[]{ "ObiectivVizitat", "OraPlecare", "FirmaTransport", "Pret", "LocuriDisponibile", "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Project.Protocol.Bilet), global::Project.Protocol.Bilet.Parser, new[]{ "NumarPersoane", "NumeClient", "NumarTelefonClient", "IdExcursie", "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Project.Protocol.ProjectRequest), global::Project.Protocol.ProjectRequest.Parser, new[]{ "Type", "User", "Bilet", "Excursie", "Oramin", "Oramax" }, null, new[]{ typeof(global::Project.Protocol.ProjectRequest.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Project.Protocol.ProjectResponse), global::Project.Protocol.ProjectResponse.Parser, new[]{ "Type", "ErrorMessage", "User", "Excursii", "Bilet" }, null, new[]{ typeof(global::Project.Protocol.ProjectResponse.Types.Type) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class User : pb::IMessage<User>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<User> _parser = new pb::MessageParser<User>(() => new User());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<User> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Project.Protocol.ProjectReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public User() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public User(User other) : this() {
      id_ = other.id_;
      username_ = other.username_;
      password_ = other.password_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public User Clone() {
      return new User(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 2;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 3;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as User);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(User other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Username != other.Username) return false;
      if (Password != other.Password) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(User other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Username = input.ReadString();
            break;
          }
          case 26: {
            Password = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Username = input.ReadString();
            break;
          }
          case 26: {
            Password = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Excursie : pb::IMessage<Excursie>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Excursie> _parser = new pb::MessageParser<Excursie>(() => new Excursie());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Excursie> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Project.Protocol.ProjectReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Excursie() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Excursie(Excursie other) : this() {
      obiectivVizitat_ = other.obiectivVizitat_;
      oraPlecare_ = other.oraPlecare_;
      firmaTransport_ = other.firmaTransport_;
      pret_ = other.pret_;
      locuriDisponibile_ = other.locuriDisponibile_;
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Excursie Clone() {
      return new Excursie(this);
    }

    /// <summary>Field number for the "obiectivVizitat" field.</summary>
    public const int ObiectivVizitatFieldNumber = 1;
    private string obiectivVizitat_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ObiectivVizitat {
      get { return obiectivVizitat_; }
      set {
        obiectivVizitat_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "oraPlecare" field.</summary>
    public const int OraPlecareFieldNumber = 2;
    private string oraPlecare_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OraPlecare {
      get { return oraPlecare_; }
      set {
        oraPlecare_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "firmaTransport" field.</summary>
    public const int FirmaTransportFieldNumber = 3;
    private string firmaTransport_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FirmaTransport {
      get { return firmaTransport_; }
      set {
        firmaTransport_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pret" field.</summary>
    public const int PretFieldNumber = 4;
    private string pret_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Pret {
      get { return pret_; }
      set {
        pret_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "locuriDisponibile" field.</summary>
    public const int LocuriDisponibileFieldNumber = 5;
    private string locuriDisponibile_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LocuriDisponibile {
      get { return locuriDisponibile_; }
      set {
        locuriDisponibile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 6;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Excursie);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Excursie other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ObiectivVizitat != other.ObiectivVizitat) return false;
      if (OraPlecare != other.OraPlecare) return false;
      if (FirmaTransport != other.FirmaTransport) return false;
      if (Pret != other.Pret) return false;
      if (LocuriDisponibile != other.LocuriDisponibile) return false;
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ObiectivVizitat.Length != 0) hash ^= ObiectivVizitat.GetHashCode();
      if (OraPlecare.Length != 0) hash ^= OraPlecare.GetHashCode();
      if (FirmaTransport.Length != 0) hash ^= FirmaTransport.GetHashCode();
      if (Pret.Length != 0) hash ^= Pret.GetHashCode();
      if (LocuriDisponibile.Length != 0) hash ^= LocuriDisponibile.GetHashCode();
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ObiectivVizitat.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ObiectivVizitat);
      }
      if (OraPlecare.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OraPlecare);
      }
      if (FirmaTransport.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(FirmaTransport);
      }
      if (Pret.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Pret);
      }
      if (LocuriDisponibile.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(LocuriDisponibile);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ObiectivVizitat.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ObiectivVizitat);
      }
      if (OraPlecare.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OraPlecare);
      }
      if (FirmaTransport.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(FirmaTransport);
      }
      if (Pret.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Pret);
      }
      if (LocuriDisponibile.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(LocuriDisponibile);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ObiectivVizitat.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ObiectivVizitat);
      }
      if (OraPlecare.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OraPlecare);
      }
      if (FirmaTransport.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FirmaTransport);
      }
      if (Pret.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Pret);
      }
      if (LocuriDisponibile.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LocuriDisponibile);
      }
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Excursie other) {
      if (other == null) {
        return;
      }
      if (other.ObiectivVizitat.Length != 0) {
        ObiectivVizitat = other.ObiectivVizitat;
      }
      if (other.OraPlecare.Length != 0) {
        OraPlecare = other.OraPlecare;
      }
      if (other.FirmaTransport.Length != 0) {
        FirmaTransport = other.FirmaTransport;
      }
      if (other.Pret.Length != 0) {
        Pret = other.Pret;
      }
      if (other.LocuriDisponibile.Length != 0) {
        LocuriDisponibile = other.LocuriDisponibile;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ObiectivVizitat = input.ReadString();
            break;
          }
          case 18: {
            OraPlecare = input.ReadString();
            break;
          }
          case 26: {
            FirmaTransport = input.ReadString();
            break;
          }
          case 34: {
            Pret = input.ReadString();
            break;
          }
          case 42: {
            LocuriDisponibile = input.ReadString();
            break;
          }
          case 50: {
            Id = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ObiectivVizitat = input.ReadString();
            break;
          }
          case 18: {
            OraPlecare = input.ReadString();
            break;
          }
          case 26: {
            FirmaTransport = input.ReadString();
            break;
          }
          case 34: {
            Pret = input.ReadString();
            break;
          }
          case 42: {
            LocuriDisponibile = input.ReadString();
            break;
          }
          case 50: {
            Id = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Bilet : pb::IMessage<Bilet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Bilet> _parser = new pb::MessageParser<Bilet>(() => new Bilet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Bilet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Project.Protocol.ProjectReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Bilet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Bilet(Bilet other) : this() {
      numarPersoane_ = other.numarPersoane_;
      numeClient_ = other.numeClient_;
      numarTelefonClient_ = other.numarTelefonClient_;
      idExcursie_ = other.idExcursie_;
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Bilet Clone() {
      return new Bilet(this);
    }

    /// <summary>Field number for the "numarPersoane" field.</summary>
    public const int NumarPersoaneFieldNumber = 1;
    private string numarPersoane_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NumarPersoane {
      get { return numarPersoane_; }
      set {
        numarPersoane_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "numeClient" field.</summary>
    public const int NumeClientFieldNumber = 2;
    private string numeClient_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NumeClient {
      get { return numeClient_; }
      set {
        numeClient_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "numarTelefonClient" field.</summary>
    public const int NumarTelefonClientFieldNumber = 3;
    private string numarTelefonClient_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NumarTelefonClient {
      get { return numarTelefonClient_; }
      set {
        numarTelefonClient_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "idExcursie" field.</summary>
    public const int IdExcursieFieldNumber = 4;
    private string idExcursie_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdExcursie {
      get { return idExcursie_; }
      set {
        idExcursie_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 5;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Bilet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Bilet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NumarPersoane != other.NumarPersoane) return false;
      if (NumeClient != other.NumeClient) return false;
      if (NumarTelefonClient != other.NumarTelefonClient) return false;
      if (IdExcursie != other.IdExcursie) return false;
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (NumarPersoane.Length != 0) hash ^= NumarPersoane.GetHashCode();
      if (NumeClient.Length != 0) hash ^= NumeClient.GetHashCode();
      if (NumarTelefonClient.Length != 0) hash ^= NumarTelefonClient.GetHashCode();
      if (IdExcursie.Length != 0) hash ^= IdExcursie.GetHashCode();
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (NumarPersoane.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(NumarPersoane);
      }
      if (NumeClient.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NumeClient);
      }
      if (NumarTelefonClient.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NumarTelefonClient);
      }
      if (IdExcursie.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(IdExcursie);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (NumarPersoane.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(NumarPersoane);
      }
      if (NumeClient.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NumeClient);
      }
      if (NumarTelefonClient.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NumarTelefonClient);
      }
      if (IdExcursie.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(IdExcursie);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (NumarPersoane.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumarPersoane);
      }
      if (NumeClient.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeClient);
      }
      if (NumarTelefonClient.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumarTelefonClient);
      }
      if (IdExcursie.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdExcursie);
      }
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Bilet other) {
      if (other == null) {
        return;
      }
      if (other.NumarPersoane.Length != 0) {
        NumarPersoane = other.NumarPersoane;
      }
      if (other.NumeClient.Length != 0) {
        NumeClient = other.NumeClient;
      }
      if (other.NumarTelefonClient.Length != 0) {
        NumarTelefonClient = other.NumarTelefonClient;
      }
      if (other.IdExcursie.Length != 0) {
        IdExcursie = other.IdExcursie;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            NumarPersoane = input.ReadString();
            break;
          }
          case 18: {
            NumeClient = input.ReadString();
            break;
          }
          case 26: {
            NumarTelefonClient = input.ReadString();
            break;
          }
          case 34: {
            IdExcursie = input.ReadString();
            break;
          }
          case 42: {
            Id = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            NumarPersoane = input.ReadString();
            break;
          }
          case 18: {
            NumeClient = input.ReadString();
            break;
          }
          case 26: {
            NumarTelefonClient = input.ReadString();
            break;
          }
          case 34: {
            IdExcursie = input.ReadString();
            break;
          }
          case 42: {
            Id = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ProjectRequest : pb::IMessage<ProjectRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProjectRequest> _parser = new pb::MessageParser<ProjectRequest>(() => new ProjectRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProjectRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Project.Protocol.ProjectReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProjectRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProjectRequest(ProjectRequest other) : this() {
      type_ = other.type_;
      user_ = other.user_ != null ? other.user_.Clone() : null;
      bilet_ = other.bilet_ != null ? other.bilet_.Clone() : null;
      excursie_ = other.excursie_ != null ? other.excursie_.Clone() : null;
      oramin_ = other.oramin_;
      oramax_ = other.oramax_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProjectRequest Clone() {
      return new ProjectRequest(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Project.Protocol.ProjectRequest.Types.Type type_ = global::Project.Protocol.ProjectRequest.Types.Type.Login;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Project.Protocol.ProjectRequest.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 2;
    private global::Project.Protocol.User user_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Project.Protocol.User User {
      get { return user_; }
      set {
        user_ = value;
      }
    }

    /// <summary>Field number for the "bilet" field.</summary>
    public const int BiletFieldNumber = 3;
    private global::Project.Protocol.Bilet bilet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Project.Protocol.Bilet Bilet {
      get { return bilet_; }
      set {
        bilet_ = value;
      }
    }

    /// <summary>Field number for the "excursie" field.</summary>
    public const int ExcursieFieldNumber = 4;
    private global::Project.Protocol.Excursie excursie_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Project.Protocol.Excursie Excursie {
      get { return excursie_; }
      set {
        excursie_ = value;
      }
    }

    /// <summary>Field number for the "oramin" field.</summary>
    public const int OraminFieldNumber = 5;
    private string oramin_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Oramin {
      get { return oramin_; }
      set {
        oramin_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "oramax" field.</summary>
    public const int OramaxFieldNumber = 6;
    private string oramax_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Oramax {
      get { return oramax_; }
      set {
        oramax_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProjectRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProjectRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(User, other.User)) return false;
      if (!object.Equals(Bilet, other.Bilet)) return false;
      if (!object.Equals(Excursie, other.Excursie)) return false;
      if (Oramin != other.Oramin) return false;
      if (Oramax != other.Oramax) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Project.Protocol.ProjectRequest.Types.Type.Login) hash ^= Type.GetHashCode();
      if (user_ != null) hash ^= User.GetHashCode();
      if (bilet_ != null) hash ^= Bilet.GetHashCode();
      if (excursie_ != null) hash ^= Excursie.GetHashCode();
      if (Oramin.Length != 0) hash ^= Oramin.GetHashCode();
      if (Oramax.Length != 0) hash ^= Oramax.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Project.Protocol.ProjectRequest.Types.Type.Login) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (user_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(User);
      }
      if (bilet_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Bilet);
      }
      if (excursie_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Excursie);
      }
      if (Oramin.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Oramin);
      }
      if (Oramax.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Oramax);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Project.Protocol.ProjectRequest.Types.Type.Login) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (user_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(User);
      }
      if (bilet_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Bilet);
      }
      if (excursie_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Excursie);
      }
      if (Oramin.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Oramin);
      }
      if (Oramax.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Oramax);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Project.Protocol.ProjectRequest.Types.Type.Login) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (user_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
      }
      if (bilet_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Bilet);
      }
      if (excursie_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Excursie);
      }
      if (Oramin.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Oramin);
      }
      if (Oramax.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Oramax);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProjectRequest other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Project.Protocol.ProjectRequest.Types.Type.Login) {
        Type = other.Type;
      }
      if (other.user_ != null) {
        if (user_ == null) {
          User = new global::Project.Protocol.User();
        }
        User.MergeFrom(other.User);
      }
      if (other.bilet_ != null) {
        if (bilet_ == null) {
          Bilet = new global::Project.Protocol.Bilet();
        }
        Bilet.MergeFrom(other.Bilet);
      }
      if (other.excursie_ != null) {
        if (excursie_ == null) {
          Excursie = new global::Project.Protocol.Excursie();
        }
        Excursie.MergeFrom(other.Excursie);
      }
      if (other.Oramin.Length != 0) {
        Oramin = other.Oramin;
      }
      if (other.Oramax.Length != 0) {
        Oramax = other.Oramax;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Project.Protocol.ProjectRequest.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            if (user_ == null) {
              User = new global::Project.Protocol.User();
            }
            input.ReadMessage(User);
            break;
          }
          case 26: {
            if (bilet_ == null) {
              Bilet = new global::Project.Protocol.Bilet();
            }
            input.ReadMessage(Bilet);
            break;
          }
          case 34: {
            if (excursie_ == null) {
              Excursie = new global::Project.Protocol.Excursie();
            }
            input.ReadMessage(Excursie);
            break;
          }
          case 42: {
            Oramin = input.ReadString();
            break;
          }
          case 50: {
            Oramax = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Project.Protocol.ProjectRequest.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            if (user_ == null) {
              User = new global::Project.Protocol.User();
            }
            input.ReadMessage(User);
            break;
          }
          case 26: {
            if (bilet_ == null) {
              Bilet = new global::Project.Protocol.Bilet();
            }
            input.ReadMessage(Bilet);
            break;
          }
          case 34: {
            if (excursie_ == null) {
              Excursie = new global::Project.Protocol.Excursie();
            }
            input.ReadMessage(Excursie);
            break;
          }
          case 42: {
            Oramin = input.ReadString();
            break;
          }
          case 50: {
            Oramax = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ProjectRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("LOGIN")] Login = 0,
        [pbr::OriginalName("LOGOUT")] Logout = 1,
        [pbr::OriginalName("GET_TRIPS")] GetTrips = 2,
        [pbr::OriginalName("GET_FILTERED_TRIPS")] GetFilteredTrips = 3,
        [pbr::OriginalName("BUY_TICKET")] BuyTicket = 4,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ProjectResponse : pb::IMessage<ProjectResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProjectResponse> _parser = new pb::MessageParser<ProjectResponse>(() => new ProjectResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProjectResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Project.Protocol.ProjectReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProjectResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProjectResponse(ProjectResponse other) : this() {
      type_ = other.type_;
      errorMessage_ = other.errorMessage_;
      user_ = other.user_ != null ? other.user_.Clone() : null;
      excursii_ = other.excursii_.Clone();
      bilet_ = other.bilet_ != null ? other.bilet_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProjectResponse Clone() {
      return new ProjectResponse(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Project.Protocol.ProjectResponse.Types.Type type_ = global::Project.Protocol.ProjectResponse.Types.Type.Ok;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Project.Protocol.ProjectResponse.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "errorMessage" field.</summary>
    public const int ErrorMessageFieldNumber = 2;
    private string errorMessage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ErrorMessage {
      get { return errorMessage_; }
      set {
        errorMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 3;
    private global::Project.Protocol.User user_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Project.Protocol.User User {
      get { return user_; }
      set {
        user_ = value;
      }
    }

    /// <summary>Field number for the "excursii" field.</summary>
    public const int ExcursiiFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Project.Protocol.Excursie> _repeated_excursii_codec
        = pb::FieldCodec.ForMessage(34, global::Project.Protocol.Excursie.Parser);
    private readonly pbc::RepeatedField<global::Project.Protocol.Excursie> excursii_ = new pbc::RepeatedField<global::Project.Protocol.Excursie>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Project.Protocol.Excursie> Excursii {
      get { return excursii_; }
    }

    /// <summary>Field number for the "bilet" field.</summary>
    public const int BiletFieldNumber = 5;
    private global::Project.Protocol.Bilet bilet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Project.Protocol.Bilet Bilet {
      get { return bilet_; }
      set {
        bilet_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProjectResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProjectResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (ErrorMessage != other.ErrorMessage) return false;
      if (!object.Equals(User, other.User)) return false;
      if(!excursii_.Equals(other.excursii_)) return false;
      if (!object.Equals(Bilet, other.Bilet)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Project.Protocol.ProjectResponse.Types.Type.Ok) hash ^= Type.GetHashCode();
      if (ErrorMessage.Length != 0) hash ^= ErrorMessage.GetHashCode();
      if (user_ != null) hash ^= User.GetHashCode();
      hash ^= excursii_.GetHashCode();
      if (bilet_ != null) hash ^= Bilet.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Project.Protocol.ProjectResponse.Types.Type.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (ErrorMessage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ErrorMessage);
      }
      if (user_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(User);
      }
      excursii_.WriteTo(output, _repeated_excursii_codec);
      if (bilet_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Bilet);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Project.Protocol.ProjectResponse.Types.Type.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (ErrorMessage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ErrorMessage);
      }
      if (user_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(User);
      }
      excursii_.WriteTo(ref output, _repeated_excursii_codec);
      if (bilet_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Bilet);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Project.Protocol.ProjectResponse.Types.Type.Ok) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (ErrorMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorMessage);
      }
      if (user_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
      }
      size += excursii_.CalculateSize(_repeated_excursii_codec);
      if (bilet_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Bilet);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProjectResponse other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Project.Protocol.ProjectResponse.Types.Type.Ok) {
        Type = other.Type;
      }
      if (other.ErrorMessage.Length != 0) {
        ErrorMessage = other.ErrorMessage;
      }
      if (other.user_ != null) {
        if (user_ == null) {
          User = new global::Project.Protocol.User();
        }
        User.MergeFrom(other.User);
      }
      excursii_.Add(other.excursii_);
      if (other.bilet_ != null) {
        if (bilet_ == null) {
          Bilet = new global::Project.Protocol.Bilet();
        }
        Bilet.MergeFrom(other.Bilet);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Project.Protocol.ProjectResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            ErrorMessage = input.ReadString();
            break;
          }
          case 26: {
            if (user_ == null) {
              User = new global::Project.Protocol.User();
            }
            input.ReadMessage(User);
            break;
          }
          case 34: {
            excursii_.AddEntriesFrom(input, _repeated_excursii_codec);
            break;
          }
          case 42: {
            if (bilet_ == null) {
              Bilet = new global::Project.Protocol.Bilet();
            }
            input.ReadMessage(Bilet);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Project.Protocol.ProjectResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            ErrorMessage = input.ReadString();
            break;
          }
          case 26: {
            if (user_ == null) {
              User = new global::Project.Protocol.User();
            }
            input.ReadMessage(User);
            break;
          }
          case 34: {
            excursii_.AddEntriesFrom(ref input, _repeated_excursii_codec);
            break;
          }
          case 42: {
            if (bilet_ == null) {
              Bilet = new global::Project.Protocol.Bilet();
            }
            input.ReadMessage(Bilet);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ProjectResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("OK")] Ok = 0,
        [pbr::OriginalName("ERROR")] Error = 1,
        [pbr::OriginalName("TRIPS")] Trips = 2,
        [pbr::OriginalName("FILTERED_TRIPS")] FilteredTrips = 3,
        [pbr::OriginalName("BOUGHT_TICKET")] BoughtTicket = 4,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
*/